name: TintHealth
version: 1.3
main: fr.mrsheepsheep.tinthealth.TintHealth
authors: [MrSheepSheep]
softdepend: [WorldGuard]
depend: [ProtocolLib]
commands:
    tinthealth:
        description: TintHealth base command
        aliases: [th, tint]
        usage: /tinthealth <subcommand>
permissions:
    tinthealth.*:
        description: Give all Tint Health commands
        children:
            tinthealth.reload: true
            tinthealth.toggle: true
            tinthealth.fade: true
    tinthealth.reload:
        description: Reloads TintHealth configuration
        default: op
    tinthealth.toggle:
        description: Allow usage of /tinthealth toggle command
        default: false
    tinthealth.fade:
        description: Allow usage of fade mode
        default: true